const GEMINI_API_KEY = process.env.GEMINI_API_KEY;

export async function generateAuraResponse({
  name,
  age,
  location,
  email,
  grievance
}) {
  const prompt = `
You are AURA, the Guardian of Human Potential, an intelligent and compassionate superhero help assistant.

Your personality:
- Calm
- Intelligent
- Kind
- Encouraging
- Practical
- Slightly futuristic
- Never overly dramatic

A person has submitted the following request:

Name: ${name}
Age: ${age}
Location: ${location}
Email: ${email}

Request:
${grievance}

Your task is to respond naturally and helpfully.

IMPORTANT:
1. Do not diagnose medical conditions.
2. Do not make assumptions about the person's feelings, personality, or life.
3. Do not use dramatic phrases such as "I can feel your pain" or "you have survived storms".
4. Do not unnecessarily repeat their age, location, or email.
5. Give practical, realistic suggestions related to their problem.
6. Give 3 to 5 simple solution ideas or tips.
7. If the request involves health, mention that persistent, worsening, or concerning symptoms should be discussed with a qualified healthcare professional.
8. If the request involves immediate danger or safety, encourage contacting a trusted person or appropriate emergency/local support.
9. Keep the response conversational rather than sounding like a formal report.
10. End with an encouraging sentence.
11. Do not claim that AURA has actually solved the person's problem.
12. Do not use markdown tables.

Structure your response like this:

A short acknowledgement.

"Here are a few things you could try:"
- Tip 1
- Tip 2
- Tip 3
- Tip 4

Then, if appropriate, mention when they should seek additional help.

Finish with one short encouraging sentence.

Keep the whole response between 120 and 220 words.
`;

  if (!GEMINI_API_KEY) {
    return fallbackResponse(grievance);
  }

  try {
    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${GEMINI_API_KEY}`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json"
        },
        body: JSON.stringify({
          contents: [
            {
              parts: [
                {
                  text: prompt
                }
              ]
            }
          ],
          generationConfig: {
            temperature: 0.7,
            maxOutputTokens: 500
          }
        })
      }
    );

    if (!response.ok) {
      throw new Error(`Gemini API error: ${response.status}`);
    }

    const data = await response.json();

    const generatedText =
      data?.candidates?.[0]?.content?.parts?.[0]?.text;

    if (!generatedText) {
      throw new Error("No response generated by Gemini");
    }

    return generatedText.trim();

  } catch (error) {
    console.error("[AURA AI ERROR]", error.message);

    return fallbackResponse(grievance);
  }
}


function fallbackResponse(grievance) {
  const text = grievance.toLowerCase();

  if (
    text.includes("tired") ||
    text.includes("stress") ||
    text.includes("health") ||
    text.includes("sleep")
  ) {
    return `
I understand. It sounds like you're looking for some practical ways to handle what you're experiencing.

Here are a few things you could try:

• Take a short break from stressful tasks and give yourself some quiet time.

• Drink enough water and try to maintain regular meals.

• Keep a consistent sleep routine and give yourself enough time to rest.

• Break larger responsibilities into smaller, manageable tasks instead of trying to handle everything at once.

• Talk to someone you trust about what you're going through rather than handling everything alone.

If tiredness or stress continues, becomes worse, or starts interfering with your everyday activities, consider speaking with a qualified healthcare professional.

You don't have to solve everything today. Focus on one small step at a time.
    `.trim();
  }

  if (
    text.includes("study") ||
    text.includes("exam") ||
    text.includes("college") ||
    text.includes("school")
  ) {
    return `
Let's turn the problem into a few manageable steps.

Here are a few things you could try:

• Break your study material into smaller topics.

• Set one realistic goal for each study session.

• Use short focused study periods followed by brief breaks.

• Practice recalling what you learned instead of only rereading it.

• Keep track of difficult topics and return to them later.

If you're feeling overwhelmed, consider talking to a teacher, mentor, or someone you trust.

Progress doesn't have to happen all at once. One focused step is still progress.
    `.trim();
  }

  if (
    text.includes("unsafe") ||
    text.includes("danger") ||
    text.includes("threat")
  ) {
    return `
Your safety should come first.

Here are a few things you could consider:

• Move to a safer place if you can do so safely.

• Stay near people you trust rather than dealing with the situation alone.

• Tell a trusted adult, family member, teacher, or another responsible person.

• Keep important contact information available.

• If there is an immediate danger, contact the appropriate local emergency service.

You don't have to handle a serious safety situation by yourself.
    `.trim();
  }

  return `
Thank you for explaining your situation. Let's break it down into something manageable.

Here are a few things you could try:

• Identify the most important part of the problem first.

• Break it into smaller steps rather than trying to solve everything at once.

• Write down a few possible solutions and consider the advantages of each.

• Talk to someone you trust if you need another perspective.

• Take one practical step today, even if it is a small one.

If the situation is serious or continues to affect your everyday life, consider seeking help from an appropriate professional or trusted person.

Every problem can be approached one step at a time.
  `.trim();
}