import nodemailer from 'nodemailer';

const transporter = nodemailer.createTransport({
  service: 'gmail',
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_APP_PASSWORD
  }
});

export async function sendGrievanceEmail({
  trackingId,
  name,
  age,
  location,
  email,
  grievance,
  createdAt
}) {

  // ==========================================
  // EMAIL 1 — SEND TO CANDIDATE / ADMIN
  // ==========================================

  const candidateMail = {
    from: `"AURA Help Portal" <${process.env.EMAIL_USER}>`,
    to: process.env.CANDIDATE_EMAIL,

    subject: `AURA Grievance Received - ${trackingId}`,

    text: `
AURA - Guardian of Human Potential
===================================

A new grievance/request has been submitted.

Transmission ID: ${trackingId}

Visitor Details
---------------
Name: ${name}
Age: ${age}
Location: ${location}
Email: ${email}

Grievance / Request
-------------------
${grievance}

Submitted
---------
${createdAt}

===================================
This message was automatically generated by the AURA Superhero Help Portal.
    `.trim()
  };


  // ==========================================
  // EMAIL 2 — SEND CONFIRMATION TO VISITOR
  // ==========================================

  const visitorMail = {
    from: `"AURA Help Portal" <${process.env.EMAIL_USER}>`,
    to: email,

    subject: `AURA Request Received - ${trackingId}`,

    text: `
Hello ${name},

AURA has received your request.

===================================

Transmission ID:
${trackingId}

Your Details
------------
Name: ${name}
Age: ${age}
Location: ${location}
Email: ${email}

Your Request
------------
${grievance}

Submitted
---------
${createdAt}

===================================

Your request has been successfully received by the AURA Help Portal.

Please keep your Transmission ID for your reference:

${trackingId}

Every problem has a path forward.

— AURA
Guardian of Human Potential
    `.trim()
  };


  // ==========================================
  // SEND BOTH EMAILS
  // ==========================================

  await transporter.sendMail(candidateMail);

  await transporter.sendMail(visitorMail);


  console.log(
    `[AURA EMAIL] Candidate and visitor emails sent successfully for ${trackingId}`
  );
}